version: 2
updates:
  # Ensure root composer is up-to-date
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies

  # Ensure module composer is up-to-date
  - package-ecosystem: composer
    directory: /modules/btcpay
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies

  # Ensure workflows are up-to-date
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - BitcoinMitchell
    labels:
      - dependencies
