branches:
  - 7.x
name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
change-template: '- #$NUMBER: $TITLE by @$AUTHOR'
template: |
  # Changes

  $CHANGES
