version: '3'
services:
  btcpayserver:
    container_name: prestashop_btcpayserver
    environment:
      BTCPAY_POSTGRES: >-
        User ID=postgres;Host=postgres;Port=5432;Application
        Name=btcpayserver;Database=btcpayserverregtest
      BTCPAY_EXPLORERPOSTGRES: >-
        User ID=postgres;Host=postgres;Port=5432;Application
        Name=btcpayserver;MaxPoolSize=80;Database=nbxplorerregtest
      BTCPAY_NETWORK: regtest
      BTCPAY_BIND: '0.0.0.0:49392'
      BTCPAY_ROOTPATH: /
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: 'https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest'
      BTCPAY_DOCKERDEPLOYMENT: 'true'
      BTCPAY_CHAINS: btc
      BTCPAY_BTCEXPLORERURL: 'http://nbxplorer:32838/'
    expose:
      - '49392'
    image: 'btcpayserver/btcpayserver:1.12.5'
    links:
      - postgres
    ports:
      - '49392:49392'
    volumes:
      - 'btcpay_datadir:/datadir'
      - 'nbxplorer_datadir:/root/.nbxplorer'
      - 'btcpay_pluginsdir:/root/.btcpayserver/Plugins'

  bitcoind:
    container_name: prestashop_bitcoind
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_WALLETDIR: /walletdata
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
        prune=50000
        mempoolfullrbf=1
    expose:
      - '43782'
      - '39388'
    image: 'btcpayserver/bitcoin:26.0'
    ports:
      - '18443:43782'
    volumes:
      - 'bitcoin_datadir:/data'
      - 'bitcoin_wallet_datadir:/walletdata'

  nbxplorer:
    container_name: prestashop_nbxplorer
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: '0.0.0.0:32838'
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: >-
        User ID=postgres;Host=postgres;Port=5432;Application
        Name=nbxplorer;MaxPoolSize=20;Database=nbxplorerregtest
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_DELETEAFTERMIGRATION: 1
      NBXPLORER_CHAINS: btc
      NBXPLORER_BTCRPCURL: 'http://bitcoind:43782/'
      NBXPLORER_BTCNODEENDPOINT: 'bitcoind:39388'
    expose:
      - '32838'
    image: 'nicolasdorier/nbxplorer:2.5.0'
    links:
      - postgres
    volumes:
      - 'nbxplorer_datadir:/datadir'
      - 'bitcoin_datadir:/root/.bitcoin'

  postgres:
    command:
      - '-c'
      - random_page_cost=1.0
      - '-c'
      - shared_preload_libraries=pg_stat_statements
    container_name: prestashop_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'btcpayserver/postgres:13.13'
    shm_size: 256mb
    volumes:
      - 'postgres_datadir:/var/lib/postgresql/data'

  mariadb:
    container_name: prestashop_mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_USER=prestashop
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=prestashop
    image: 'bitnami/mariadb:11.0'
    ports:
      - '3305:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  prestashop:
    container_name: prestashop_prestashop
    depends_on:
      - mariadb
      - btcpayserver
    environment:
      - PRESTASHOP_HOST=prestashop:8080
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=prestashop
      - PRESTASHOP_DATABASE_PASSWORD=bitnami
      - PRESTASHOP_DATABASE_NAME=prestashop
      - PRESTASHOP_EMAIL=user@example.com
      - PRESTASHOP_PASSWORD=bitnami1
    expose:
      - '8080'
      - '8443'
    image: 'bitnami/prestashop:8.1.3'
    links:
      - mariadb
      - btcpayserver
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'prestashop_data:/bitnami/prestashop'

  mailhog:
    container_name: prestashop_mailhog
    image: 'mailhog/mailhog:latest'
    logging:
      driver: none
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  bitcoin_datadir: ~
  bitcoin_wallet_datadir: ~
  btcpay_datadir: ~
  btcpay_pluginsdir: ~
  mariadb_data: { driver: local }
  nbxplorer_datadir: ~
  postgres_datadir: ~
  prestashop_data: { driver: local }
