name: 🚀 Feature request
description: Suggest a new feature or enhancement
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request!
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/btcpayserver/prestashop-plugin/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the repository [issues](https://github.com/btcpayserver/prestashop-plugin/issues) and found no similar feature requests.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in this module?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?
  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
