admin_btcpay_configure:
  path: /btcpay/configure
  methods: [GET]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::editAction'
    _legacy_controller: AdminConfigureBTCPay
    _legacy_link: AdminConfigureBTCPay
    _disable_module_prefix: true

admin_btcpay_configure_process:
  path: /btcpay/configure
  methods: [GET, POST]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::editProcessAction'
    _legacy_controller: AdminConfigureBTCPay
    _disable_module_prefix: true

admin_btcpay_validate:
  path: /btcpay/api-key/validate
  methods: [GET, POST]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::validateAction'
    _legacy_controller: AdminConfigureBTCPay
    _disable_module_prefix: true

