admin_btcpay_configure:
  path: /btcpay/configure
  methods: [GET]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::viewAction'
    _legacy_controller: AdminConfigureBTCPay
    _legacy_link: AdminConfigureBTCPay
    _disable_module_prefix: true

admin_btcpay_configure_server_process:
  path: /btcpay/configure
  methods: [GET, POST]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::editServerSettingsAction'
    _legacy_controller: AdminConfigureBTCPay
    _disable_module_prefix: true

admin_btcpay_configure_general_process:
  path: /btcpay/configure/general
  methods: [GET, POST]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::editGeneralSettingsAction'
    _legacy_controller: AdminConfigureBTCPay
    _disable_module_prefix: true

admin_btcpay_validate:
  path: /btcpay/api-key/validate
  methods: [GET, POST]
  defaults:
    _controller: 'BTCPay\Controller\Admin\Improve\Payment\ConfigureController::validateAPIKeyAction'
    _legacy_controller: AdminConfigureBTCPay
    _disable_module_prefix: true
