services:
  _defaults:
    public: true

  prestashop.module.btcpay:
    class: BTCPay

  prestashop.module.btcpay.repository:
    class: BTCPay\Repository\BitcoinPaymentRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  BTCPay\Controller\Admin\Improve\Payment\ConfigureController:
    class: BTCPay\Controller\Admin\Improve\Payment\ConfigureController
    arguments:
      - '@validator'

  # BTCPay form data provider
  prestashop.module.btcpay.form.configure.provider:
    class: BTCPay\Form\ConfigureFormDataProvider

  # Form types
  prestashop.module.btcpay.form.type.configure:
    class: BTCPay\Form\Type\ConfigureType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # BTCPay form handler
  prestashop.module.btcpay.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $formDataProvider: '@prestashop.module.btcpay.form.configure.provider'
      $formTypes:
        'btcpay': 'BTCPay\Form\Type\ConfigureType'
      $hookName: 'AdminConfigureBTCPay'
