name: "Validate"

on:
  push:
    paths: [ 'modules/**' ]
    branches: [ '6.x' ]
    tags: [ 'v*' ]
  pull_request:
    paths: [ 'modules/**' ]

permissions: {}

jobs:
  linting:
    name: "Linting (PHP ${{ matrix.php-versions }})"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1' ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5" # v6.0.0
        with:
          persist-credentials: false
      - name: "Setup PHP, with composer and extensions"
        uses: "shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f" # v2.37.0
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "mbstring, xml, ctype, iconv, intl, gd"
          tools: "composer:v2"
      - name: "Get composer cache directory"
        id: "composer-cache"
        run: 'echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT'
      - name: "Cache composer dependencies"
        uses: "actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306" # v5.0.3
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ runner.os }}-composer-"
          lookup-only: true
      - name: "Validate composer"
        run: "composer validate"
      - name: "Install Composer dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader"

      # Ensure our code looks proper
      - name: "Lint the code"
        run: "make lint"
